### PR TITLE
Dashboard improvements, Segments Fragment

### PR DESCRIPTION
**Pull request by erikbdev**
Hello!

This pull request includes improvements on Dashboard showing the first selected segment or the first segment if no segment was selected and you can change the color of each of the segment's index.

You can also change the brightness and every time you manually refresh it, it updates the value based on the new data.

I also implemented a Segment fragment to view your segments and view. As of now, there is no implementation on editing segments but it's progress.

Effects reflect from the first/selected segment and sets the effect speed and intensity and you can change it.

This pull request also updates the api to 30.

If there are any issues or can't be merged let me know!

### CODE REVIEW

**Comment by Leeonardoo** [comment]
Hey! Thanks for your contribution! I'll be sure to take a better look tomorrow but so far seems great to me. Also I plan to get this project back to life as I have learned some new things in the past months, so you can expect new stuff coming soon too!

**Comment by erikbdev** [comment]
Awesome! Can't wait to add more features! I am also planning on working an app for iOS too!

**Comment by Leeonardoo** [comment]
Just as an update, I just tested it and it seems like I can't actually change the colors of each segment, and the new SegmentsFragment doesn't save it's state when navigating. I'll push a new commit later tonight also getting this to work and I'll probably make some changes to the UI later on

**Comment by erikbdev** [comment]
So far the SegmentFragment just shows the segments. There are no listeners attached to any viewed other than expanding/collapsing segment information, but no implementation on sending the new information to our WLED device

I wasn't sure how to communicate it since I would need to get the data back on the recycler view that was clicked plus all the new data that the user wants to send 😬

And saved state hasn't been worked on yet but I can implement that later today

**Comment by Leeonardoo** [comment]
Cool. I merged it for now, and I'll be making some new updates related to this. Feel free to open any new PRs

**Pull request merged**
